### ISSUE TITLE
[iOS] 레이블, 마일스톤 생성 공통뷰 구현

### ISSUE THREAD

**Issue by eojine** [boostcamp-2020/IssueTracker-11#3]
## :bulb: 이슈 내용
- 레이블, 마일스톤 생성에서 쓰일 공통된 뷰 구현
- 두 상황에서 각각 설정 가능하게 구성
  - 레이블 생성
  <img width="228" alt="스크린샷 2020-10-29 오후 1 45 44" src="https://user-images.githubusercontent.com/15014017/97526753-285c1900-19ed-11eb-858f-e272d35612bc.png">

  - 마일스톤 생성
  <img width="228" alt="스크린샷 2020-10-29 오후 1 45 53" src="https://user-images.githubusercontent.com/15014017/97526780-390c8f00-19ed-11eb-9508-39cfa8af68df.png">

## :white_check_mark: 작업 내용
- [x] 공통뷰 구현

**Comment by Jeonghae10** [comment]
ㅠ
